services:
  generator:
    build: ./generator
    container_name: generator
    volumes:
      - ./media/input:/input
      - ./media/output:/output
    environment:
      - THUMB_EVERY_SEC=2
      - THUMB_WIDTH=320
    restart: unless-stopped

  streamer:
    image: nginx:alpine
    container_name: streamer
    volumes:
      - ./media/output:/usr/share/nginx/html:ro
      - ./streamer/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    restart: unless-stopped

  player:
    build: ./player
    container_name: player
    volumes:
      - ./player/index.html:/usr/share/nginx/html/index.html:rw
      - ./player/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      # Points at the streamer service inside the compose network
      - CONTENT_BASE=http://streamer:80
    ports:
      - "8080:80"
    restart: unless-stopped